package com.claireyurev;
/*
 *   ProjectEuler.net
 *   Problem 2: Even Fibonacci numbers
 *   Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * */

public class Main {

    public static void main(String[] args) {

        // Basic Fibonacci series

        double max = 8;
        double a = 1;
        double b = 2;

        System.out.println("Fib. series of "+max+"numbers");

        for(double i = 1; i < max; ++i){

            System.out.println(a+" ");

            double rollingSum = a + b;
            a = b;
            b = rollingSum;

        }

    }
}
